backend:
  name: github
  repo: sotuonunyo/candle-shop
  branch: main
  open_authoring: true

# Optional: Add this to prevent caching issues
publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_data"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
